[package]
name = "trust"
version = "0.1.0"
authors = ["Antonio Astorino <antonio.astorino.ing@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tun-tap-new = "0.1.0"